### ISSUE TITLE
Play Times Not Displaying Properly With Player Tags

### ISSUE THREAD

**Issue by CharlieDelune** [Infiziert90/BetterPlaytime#1]
The following is happening even after having executed /playtime once on my main character. I even tried relogging and doing /playtime again to fix it, but it persists.

'/btime ui' brings up a window that only says "Total: 6 minutes"

'/btime' on its own just echoes my character's name twice.

I have 330 days played on this character, so 6 minutes doesn't seem quite right to me.

There are no exceptions in my dalamud.log

EDIT: This turns out to be an incompatibility with Player Tags. Disabling player tags allows /btime to display properly. Re-enabling it breaks /btime again.

**Comment by CharlieDelune** [comment]
More information:

I logged into another character to see what would happen. The _previous character's time_ is displaying when I '/btime' but the current character's name just gets echoed twice. When I switched back to the previous character, they swapped - put more succinctly: the currently logged in character's time never displays, only the character's name where the time should go.

For '/btime ui' I could be radically misunderstanding what it's supposed to be doing, but it's pretty much only ever showing playtime since installing the mod and nothing for specific characters.

**Comment by Infiziert90** [comment]
/btime ui is just displaying the current session time, so 6min seems right :)

That /btime itself not picks up your /playtime is a known issue, sadly none of the other people having it have responded to me, so if you would be so kind to post the result of your /playtime, that would help me alot

**Comment by CharlieDelune** [comment]
Result of /playtime:

[10:12 a.m.]Total Play Time: 329 days, 21 hours, 24 minutes

**Comment by CharlieDelune** [comment]
> /btime ui is just displaying the current session time, so 6min seems right :)

Ah, alright. So this is working properly then, I just misunderstood what it was supposed to be doing.

**Comment by Infiziert90** [comment]
> The following is happening even after having executed /playtime once on my main character. I even tried relogging and doing /playtime again to fix it, but it persists.
> 
> '/btime ui' brings up a window that only says "Total: 6 minutes"
> 
> '/btime' on its own just echoes my character's name twice.
> 
> I have 330 days played on this character, so 6 minutes doesn't seem quite right to me.
> 
> There are no exceptions in my dalamud.log

Just tried it after deleting my config, and it works just fine for me ... making it harder for me to understand why this is happening

> [16:23]Character NameServer: 300 days, 9 hours, 46 minutes

After adding another character, both will be printed + a message of the total from both

**Comment by CharlieDelune** [comment]
> After adding another character, both will be printed + a message of the total from both

It actually doesn't. Whatever character I'm currently logged into, the time doesn't display, only the name (twice). The times for my other characters display, and the total is correct, but it's always whatever the currently logged in character is that doesn't display.

> [10:32 a.m.]Character Name1Character Name1
> [10:32 a.m.]Character Name2Server: 19 days
> [10:32 a.m.]Character Name3Server: 15 days
> [10:32 a.m.]Across all characters, you have played for: 364 days

> [10:34 a.m.]Character Name2Character Name2
> [10:34 a.m.]Character Name1Server: 329 days
> [10:34 a.m.]Character Name3Server: 15 days
> [10:34 a.m.]Across all characters, you have played for: 364 days

If I only have one character added, I just get 
> [10:37 a.m.]Character Name1Character Name1

and nothing else.

**Comment by Infiziert90** [comment]
I'm out of ideas why that could happen, the string format doesn't even fit what gets printed

```Plugin.Chat.Print($"{currentChar.Playername}: {GeneratePlaytime(currentChar.PTime)}");```

so there is parts missing like the ": " in the current character

**Comment by CharlieDelune** [comment]
Looks like there's an incompatibility with the Player Tags plugin. Disabling Player Tags allows /btime to display properly. Re-enabling it causes /btime to break again.

Had a hunch it might have been an incompatibility after you said you couldn't replicate. Plan was to disable all of my plugins and re-enable them one-by-one, but since Player Tags alters the way a player's name looks, I thought I'd try that one first. Lo and behold, that was it. I'd have tried this sooner, but Island Sanctuary called.

**Comment by Infiziert90** [comment]
Thanking yoyu for figuring it out, already writing with the dev of PlayerTags, maybe there is a fix to it

**Comment by CharlieDelune** [comment]
No problem, thanks for being so responsive! Good luck!

**Comment by Infiziert90** [comment]
Fixed in PlayerTags, update should come soon, so gonna close this :)

**Comment by CharlieDelune** [comment]
Awesome :D
