### ISSUE TITLE
Request: integrate with Dalamud Server Info Bar

### ISSUE THREAD

**Issue by chernobog** [Infiziert90/BetterPlaytime#3]
Please add options for displaying Better Playtime in the Server Info Bar via Dalamud.

**Comment by Infiziert90** [comment]
The current session time or full playtime?

**Comment by chernobog** [comment]
At the very least, the current session.

**Comment by Infiziert90** [comment]
Implemented in the latest update :)
For now it is just the total session playtime, maybe per character session and more comes later

**Comment by chernobog** [comment]
Thank you so much for the quick implementation!
